src/Entity/CentroEducativo.php
<?php

namespace App\Entity;

use App\Repository\CentroEducativoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CentroEducativoRepository::class)]
class CentroEducativo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $concello_id = null;

    #[ORM\Column]
    private ?int $titularidad_id = null;

    #[ORM\Column(length: 100)]
    private ?string $nombre = null;

    #[ORM\Column(length: 100)]
    private ?string $direccion = null;

    #[ORM\Column(length: 5)]
    private ?string $cod_postal = null;

    #[ORM\Column(length: 9, nullable: true)]
    private ?string $telefono = null;

    #[ORM\Column]
    private ?float $coordenada_x = null;

    #[ORM\Column]
    private ?float $coordenada_y = null;

    #[ORM\Column(length: 20)]
    private ?string $tipo_de_centro = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Concello $concello = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getConcelloId(): ?int
    {
        return $this->concello_id;
    }

    public function setConcelloId(int $concello_id): static
    {
        $this->concello_id = $concello_id;

        return $this;
    }

    public function getTitularidadId(): ?int
    {
        return $this->titularidad_id;
    }

    public function setTitularidadId(int $titularidad_id): static
    {
        $this->titularidad_id = $titularidad_id;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(string $direccion): static
    {
        $this->direccion = $direccion;

        return $this;
    }

    public function getCodPostal(): ?string
    {
        return $this->cod_postal;
    }

    public function setCodPostal(string $cod_postal): static
    {
        $this->cod_postal = $cod_postal;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(?string $telefono): static
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getCoordenadaX(): ?float
    {
        return $this->coordenada_x;
    }

    public function setCoordenadaX(float $coordenada_x): static
    {
        $this->coordenada_x = $coordenada_x;

        return $this;
    }

    public function getCoordenadaY(): ?float
    {
        return $this->coordenada_y;
    }

    public function setCoordenadaY(float $coordenada_y): static
    {
        $this->coordenada_y = $coordenada_y;

        return $this;
    }

    public function getTipoDeCentro(): ?string
    {
        return $this->tipo_de_centro;
    }

    public function setTipoDeCentro(string $tipo_de_centro): static
    {
        $this->tipo_de_centro = $tipo_de_centro;

        return $this;
    }

    public function getConcello(): ?Concello
    {
        return $this->concello;
    }

    public function setConcello(?Concello $concello): static
    {
        $this->concello = $concello;

        return $this;
    }

    public function __toString()
    {
        return ($this->getId() . "-" . $this->getConcelloId() . "-" . $this->getTitularidadId() . "-" . $this->getNombre()
        . "-" . $this->getDireccion() . "-" . $this->getCodPostal() . "-" . $this->getTelefono()
        . "-" . $this->getCoordenadaX() . "-" . $this->getCoordenadaY() . $this->getTipoDeCentro());
    }
}

src/Controller/BuscadorController.php
<?php

namespace App\Controller;

use App\Service\CentroService;
use App\Service\ConcelloService;
use App\Service\TitularidadService;
use App\Service\TipoCentroService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BuscadorController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function redirectToindex(): Response
    {
        return $this->redirectToRoute('app_buscador');
    }

    #[Route('/buscador', name: 'app_buscador')]
    public function index(ConcelloService $concelloService, TipoCentroService $tipoCentroService): Response
    {
        $concellos = $this->getGroupedConcellos($concelloService);
        $tipos_de_centro = $this->getTiposCentro($tipoCentroService);
        return $this->render('buscador/index.html.twig', [
            'controller_name' => 'BuscadorController',
            'concellos' => $concellos,
            'tipos_centro' => $tipos_de_centro,
        ]);
    }

    #[Route('/buscador/list', name: 'app_buscador_list')]
    public function list(ConcelloService $concelloService, TipoCentroService $tipoCentroService, CentroService $centroService): Response {
        $concellos = $this->getGroupedConcellos($concelloService);
        $tipos_de_centro = $this->getTiposCentro($tipoCentroService);
        $valido = false;
        $keys = array_keys($_GET);

        for ($i = 0; $i < count($keys) && !$valido; $i++) {
            if (isset($_GET[$keys[$i]]) && !empty($_GET[$keys[$i]])) {
                $valido = true;
            }
        }

        if (!$valido) {
            return $this->render('buscador/index.html.twig', [
                'controller_name' => 'BuscadorController',
                'concellos' => $concellos,
                'tipos_centro' => $tipos_de_centro,
                'type' => 'error',
                'message' => 'Cubra como mínimo un campo do formulario'
            ]);
        }

        $nombre = "";
        if (isset($_GET["nombre"]) && !empty($_GET["nombre"])) {
            $nombre = $_GET["nombre"];
        }

        $tipo_de_centro = "";
        if (isset($_GET["tipo_centro"]) && !empty($_GET["tipo_centro"])) {
            $tipo_de_centro = $_GET["tipo_centro"];
        }

        $provincia_id = 0;
        if (isset($_GET["provincia"]) && !empty($_GET["provincia"])) {
            $provincia_id = $_GET["provincia"];
        }

        $concello_id = 0;
        if (isset($_GET["concello"]) && !empty($_GET["concello"])) {
            $concello_id = $_GET["concello"];
        }

        $titularidad_nombre = "";
        if (isset($_GET["titularidad"]) && !empty($_GET["titularidad"])) {
            $titularidad_nombre = $_GET["titularidad"];
        }

        $titularidad_dependencia = null;
        if (isset($_GET["dependencia"]) && strlen($_GET["dependencia"]) !== 0) {
            $titularidad_dependencia = $_GET["dependencia"];
        }

        $centros = $centroService->queryBuilder($nombre, $tipo_de_centro, $provincia_id, $concello_id, $titularidad_nombre, $titularidad_dependencia);

        $message = "Non se atopou ningún centro";

        if (!empty($centros)) {
            $message = "Atopáronse " . sizeof($centros) . " centro(s)";
        }

        return $this->render('buscador/index.html.twig', [
            'controller_name' => 'BuscadorController',
            'concellos' => $concellos,
            'tipos_centro' => $tipos_de_centro,
            'type' => 'normal',
            'message' => $message,
            'centros' => $centros
        ]);
    }

    public function getGroupedConcellos(ConcelloService $concelloService): array {
        $concellos = array(
            1 => $concelloService->findByProvincia(1),
            2 => $concelloService->findByProvincia(2),
            3 => $concelloService->findByProvincia(3),
            4 => $concelloService->findByProvincia(4)
        );
        return $concellos;
    }

    public function getTiposCentro(TipoCentroService $tipoCentroService) {
        return $tipoCentroService->list();
    }

    public function getTitularidadIds(TitularidadService $titularidadService, $nombre, $dependencia) {
        return $titularidadService->findBy($nombre, $dependencia);
    }
}

templates/buscador/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Buscador{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        prop_object.method = "GET";
        prop_object.action = "{{path('app_buscador_list')}}";
        let arrayConcellos = [[], [], [], []];
        let contador = 0;
        {% for groupedConcellos in concellos %}
            {% for concello in groupedConcellos %}
                arrayConcellos[contador].push("{{concello}}");
            {% endfor %}
            contador++;
        {% endfor %}
        prop_object.concellos = arrayConcellos;
        
        let arrayTiposCentro = [];
        contador = 0;
        {% for tipo in tipos_centro %}
            arrayTiposCentro[contador] = ("{{tipo}}");
            contador++;
        {% endfor %}
        prop_object.tiposCentro = arrayTiposCentro;

        let arrayCentros = [];
        let arrayCentrosCoordenadas = [];
        let nombreProvincia = "";
        let nombreConcello = "";
        contador = 0;
        {% if centros|default(null) %}
            {% for centro in centros %}
                arrayConcellos.forEach((concellos) => {
                    if (concellos.find((concello) => concello.split('-')[0] === "{{centro.concelloId}}") !== undefined ) {
                        arrayConcellos[arrayConcellos.indexOf(concellos)].forEach((concello) => {
                            if (concello.split('-')[0] === "{{centro.concelloId}}") {
                                nombreConcello = concello.split('-')[1];
                            }
                        })
                        switch(arrayConcellos.indexOf(concellos)) {
                            case 0:
                                nombreProvincia = "A Coruña";
                            break;
                            case 1:
                                nombreProvincia = "Lugo";
                            break;
                            case 2:
                                nombreProvincia = "Ourense";
                            break;
                            case 3:
                                nombreProvincia = "Pontevedra";
                            break;
                        }
                    }
                })
                arrayCentros[contador] = {
                    id: "{{centro.id}}",
                    nombre: "{{centro.nombre}}",
                    direccion: "{{centro.direccion}}",
                    concello: nombreConcello,
                    provincia: nombreProvincia,
                    cod_postal: "{{centro.codPostal}}",
                    tlf: "{{centro.telefono}}"
                };
                arrayCentrosCoordenadas[contador] = {
                    id: "{{centro.id}}",
                    nombre: "{{centro.nombre}}",
                    coordenadaX: "{{centro.coordenadaX}}",
                    coordenadaY: "{{centro.coordenadaY}}"
                }
                contador++;
            {% endfor %}
            prop_object.centros = arrayCentros;
            prop_object.centrosCoordenadas = arrayCentrosCoordenadas;
        {% endif %}
    </script>
    {% if message|default(null) %}
        <script>
            prop_object.message = "{{message}}";
            prop_object.type = "{{type}}";
        </script>
    {% endif %}
{% endblock %}
{% block body %}
    <div {{ react_component('FormApp') }}>
            Loading... <i class="fas fa-cog fa-spin fa-3x"></i>
    </div>
    <div {{ react_component('Modal') }}></div>
{% endblock %}